[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'Shougo/deol.nvim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let b:ale_linters = ['eslint']
let b:ale_linters = {'javascript': ['eslint']}
'''

